# Generated by Django 4.0.4 on 2022-07-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_giftcard_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='giftcard_id',
        ),
    ]
