# Generated by Django 4.0.4 on 2022-07-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_giftcard_giftcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='email',
            field=models.EmailField(default='237274102@qq.com', max_length=254),
        ),
    ]
